/**
 * Core setting definitions — registered at boot so getSetting/setSetting
 * can validate values and the admin settings UI can auto-discover fields.
 */
import { z } from "zod";
import { defineSettings } from "./registry";

export function registerCoreSettingDefinitions(): void {
  defineSettings([
    // ── Site ─────────────────────────────────────────────────────────────
    {
      key: "site.title",
      group: "Site",
      label: "Site title",
      description: "Shown in browser tabs and as the default title when your site is shared on social media.",
      schema: z.string().min(1).max(200),
      defaultValue: "NextPress",
      scope: "public",
    },
    {
      key: "site.tagline",
      group: "Site",
      label: "Tagline",
      description: "A short description of your site",
      schema: z.string().max(500),
      defaultValue: "",
      scope: "public",
    },
    {
      key: "site.url",
      group: "Site",
      label: "Site URL",
      description: "The public URL of your site (e.g. https://example.com)",
      schema: z.string().url().or(z.literal("")),
      defaultValue: "",
      scope: "public",
    },
    {
      key: "site.timezone",
      group: "Site",
      label: "Timezone",
      description: "Used for scheduling posts and displaying dates",
      schema: z.string().min(1),
      defaultValue: "UTC",
      scope: "public",
    },
    {
      key: "site.date_format",
      group: "Site",
      label: "Date format",
      description: "Used when rendering dates across the admin and front end",
      schema: z.enum(["yyyy-MM-dd", "MMM d, yyyy", "d MMM yyyy", "MM/dd/yyyy", "dd/MM/yyyy"]),
      defaultValue: "MMM d, yyyy",
      scope: "public",
    },
    {
      key: "site.time_format",
      group: "Site",
      label: "Time format",
      description: "12-hour clock or 24-hour clock",
      schema: z.enum(["12h", "24h"]),
      defaultValue: "12h",
      scope: "public",
    },

    // ── Email ────────────────────────────────────────────────────────────
    {
      key: "smtp.host",
      group: "Email",
      label: "SMTP host",
      schema: z.string(),
      defaultValue: "",
      scope: "private",
    },
    {
      key: "smtp.port",
      group: "Email",
      label: "SMTP port",
      schema: z.number().int().min(1).max(65535),
      defaultValue: 587,
      scope: "private",
    },
    {
      key: "smtp.user",
      group: "Email",
      label: "SMTP username",
      schema: z.string(),
      defaultValue: "",
      scope: "private",
    },
    {
      key: "smtp.password",
      group: "Email",
      label: "SMTP password",
      schema: z.string(),
      defaultValue: "",
      scope: "private",
      encrypted: true,
    },
    {
      key: "smtp.from_address",
      group: "Email",
      label: "From address",
      description: "The sender address for outgoing emails",
      schema: z.string().email().or(z.literal("")),
      defaultValue: "",
      scope: "private",
    },

    // ── Security ─────────────────────────────────────────────────────────
    {
      key: "security.lockout_threshold",
      group: "Security",
      label: "Failed-login attempts before lockout",
      description: "How many bad-password attempts before the account is temporarily locked",
      schema: z.number().int().min(1).max(50),
      defaultValue: 5,
      scope: "private",
    },
    {
      key: "security.lockout_window_minutes",
      group: "Security",
      label: "Failed-attempt counting window (minutes)",
      description: "Attempts older than this don't count toward the threshold",
      schema: z.number().int().min(1).max(1440),
      defaultValue: 15,
      scope: "private",
    },
    {
      key: "security.lockout_duration_minutes",
      group: "Security",
      label: "Lockout duration (minutes)",
      description: "How long a locked account stays locked",
      schema: z.number().int().min(1).max(1440),
      defaultValue: 30,
      scope: "private",
    },
    {
      key: "security.session_max_age_days",
      group: "Security",
      label: "Session lifetime (days)",
      description: "How long users stay signed in before being asked to log in again. Takes effect after the next restart.",
      schema: z.number().int().min(1).max(365),
      defaultValue: 30,
      scope: "private",
    },
    {
      key: "security.step_up_ttl_minutes",
      group: "Security",
      label: "Step-up re-auth window (minutes)",
      description: "How long a fresh re-authentication satisfies sensitive actions",
      schema: z.number().int().min(1).max(60),
      defaultValue: 5,
      scope: "private",
    },
    {
      key: "security.country_mode",
      group: "Security",
      label: "Country filter mode",
      description: "off = no filtering, allowlist = only listed countries allowed, denylist = listed countries blocked",
      schema: z.enum(["off", "allowlist", "denylist"]),
      defaultValue: "off",
      scope: "private",
    },
    {
      key: "security.country_codes",
      group: "Security",
      label: "Country codes",
      description: "Two-letter country codes (US, GB, DE, …), one per line. Used as the allow- or deny-list depending on the mode above.",
      schema: z.string(),
      defaultValue: "",
      scope: "private",
    },

    // ── API ──────────────────────────────────────────────────────────────
    {
      key: "api.token_default_ttl_days",
      group: "API",
      label: "Default API token lifetime (days)",
      description: "Used when creating a token without an explicit expiry. 0 = never expires.",
      schema: z.number().int().min(0).max(3650),
      defaultValue: 90,
      scope: "private",
    },
    {
      key: "api.cors_allowed_origins",
      group: "API",
      label: "Allowed CORS origins",
      description: "External sites that may call your API from a browser. One URL per line (https://example.com). Leave empty to only allow your own site.",
      schema: z.string(),
      defaultValue: "",
      scope: "private",
    },
    {
      key: "api.rate_limit_per_minute",
      group: "API",
      label: "Default rate limit (requests / minute)",
      description: "Per-token override beats this site-wide default",
      schema: z.number().int().min(1).max(10000),
      defaultValue: 60,
      scope: "private",
    },
    {
      key: "api.log_token_introspection",
      group: "API",
      label: "Log token introspection calls",
      description: "When on, every API key check is recorded in your activity log.",
      schema: z.boolean(),
      defaultValue: false,
      scope: "private",
    },

    // ── Logging ──────────────────────────────────────────────────────────
    {
      key: "logging.audit_retention_days",
      group: "Logging",
      label: "Audit log retention (days)",
      description: "Activity-log entries older than this are deleted automatically.",
      schema: z.number().int().min(1).max(3650),
      defaultValue: 365,
      scope: "private",
    },
    {
      key: "logging.system_log_retention_days",
      group: "Logging",
      label: "Request / system log retention (days)",
      schema: z.number().int().min(1).max(3650),
      defaultValue: 90,
      scope: "private",
    },
    {
      key: "logging.failed_login_retention_days",
      group: "Logging",
      label: "Failed-login retention (days)",
      schema: z.number().int().min(1).max(3650),
      defaultValue: 180,
      scope: "private",
    },
    {
      key: "logging.redaction_patterns",
      group: "Logging",
      label: "Redaction patterns",
      description: "One regex per line. Matches in log payloads are replaced with [REDACTED].",
      schema: z.string(),
      defaultValue: "",
      scope: "private",
    },
    {
      key: "logging.log_successful_logins",
      group: "Logging",
      label: "Log successful logins",
      schema: z.boolean(),
      defaultValue: true,
      scope: "private",
    },
    {
      key: "logging.log_failed_logins",
      group: "Logging",
      label: "Log failed logins",
      schema: z.boolean(),
      defaultValue: true,
      scope: "private",
    },

    // ── Maintenance ──────────────────────────────────────────────────────
    {
      key: "maintenance.enabled",
      group: "Maintenance",
      label: "Maintenance mode",
      description: "When on, your public site shows the message below to all visitors except those on the bypass list.",
      schema: z.boolean(),
      defaultValue: false,
      scope: "private",
    },
    {
      key: "maintenance.message",
      group: "Maintenance",
      label: "Maintenance message",
      description: "Shown to non-bypass visitors while maintenance mode is on",
      schema: z.string().max(500),
      defaultValue: "We'll be back shortly.",
      scope: "private",
    },
    {
      key: "maintenance.bypass_ips",
      group: "Maintenance",
      label: "Bypass IPs",
      description: "One CIDR per line. These addresses always get through, even with maintenance on.",
      schema: z.string(),
      defaultValue: "",
      scope: "private",
    },
    {
      key: "maintenance.read_only",
      group: "Maintenance",
      label: "Read-only mode",
      description: "Visitors can still browse, but no changes (sign-ups, comments, admin edits) are accepted. Useful while you're moving data or rehearsing a backup restore.",
      schema: z.boolean(),
      defaultValue: false,
      scope: "private",
    },

    // ── Content ──────────────────────────────────────────────────────────
    {
      key: "content.editor_inspector_position",
      group: "Content",
      label: "Editor inspector position",
      description:
        "Where the selected-block settings panel renders in the page/post editor. " +
        "'sidebar' keeps it pinned to the right rail; 'floating' opens a resizable, " +
        "draggable popup so the canvas can use the full width.",
      schema: z.enum(["sidebar", "floating"]),
      defaultValue: "sidebar",
      scope: "private",
    },
    {
      key: "content.home_page_id",
      group: "Content",
      label: "Homepage page",
      description:
        "Id of the Page rendered at the site root (/). 0 means unset — the " +
        "homepage shows a 'configure me' notice in that case.",
      schema: z.number().int().nonnegative(),
      defaultValue: 0,
      scope: "public",
    },
    {
      key: "content.home_source_kind",
      group: "content",
      label: "Homepage source kind",
      description:
        "What the public homepage shows when no static page is configured. " +
        "One of 'page', 'recent', 'topic', 'pillar'.",
      schema: z.enum(["page", "recent", "topic", "pillar"]),
      defaultValue: "recent",
      scope: "public",
    },
    {
      key: "content.home_topic_id",
      group: "content",
      label: "Homepage topic",
      description: "Topic id used when home_source_kind is 'topic'.",
      schema: z.number().int().nonnegative(),
      defaultValue: 0,
      scope: "public",
    },
    {
      key: "content.home_pillar_id",
      group: "content",
      label: "Homepage pillar",
      description: "Pillar (post id) used when home_source_kind is 'pillar'.",
      schema: z.number().int().nonnegative(),
      defaultValue: 0,
      scope: "public",
    },
    {
      key: "content.home_layout",
      group: "Content",
      label: "Homepage layout",
      description: "How posts are arranged on the homepage when source is Recent / Topic / Pillar.",
      schema: z.enum(["list", "grid", "plain"]),
      defaultValue: "grid",
      scope: "private",
    },
    {
      key: "content.home_limit",
      group: "Content",
      label: "Posts per page",
      description: "How many posts the homepage shows per page (1–50). Pagination uses this for slicing.",
      schema: z.number().int().min(1).max(50),
      defaultValue: 12,
      scope: "private",
    },
    {
      key: "content.home_show_thumbnail",
      group: "Content",
      label: "Show thumbnails",
      description: "Whether each post on the homepage shows its featured image.",
      schema: z.boolean(),
      defaultValue: true,
      scope: "private",
    },
    {
      key: "content.home_show_topic",
      group: "Content",
      label: "Show topic chip",
      description: "Whether each post on the homepage shows its primary topic.",
      schema: z.boolean(),
      defaultValue: false,
      scope: "private",
    },
    {
      key: "content.home_show_date",
      group: "Content",
      label: "Show date",
      description:
        "Whether each post on the homepage shows its published date. Applies to the Recent / Topic / Pillar source kinds (the Page kind renders a static page body and ignores this).",
      schema: z.boolean(),
      defaultValue: true,
      scope: "private",
    },
    {
      key: "content.home_grid_columns",
      group: "Content",
      label: "Grid columns",
      description: "Cards per row in grid layout (2, 3, or 4).",
      schema: z.union([z.literal(2), z.literal(3), z.literal(4)]),
      defaultValue: 2,
      scope: "private",
    },
    {
      key: "content.home_grid_aspect",
      group: "Content",
      label: "Grid image aspect",
      description: "Thumbnail aspect ratio in grid layout: rectangle (16:9) or square (1:1).",
      schema: z.enum(["rectangle", "square"]),
      defaultValue: "rectangle",
      scope: "private",
    },
    {
      key: "content.home_pagination_enabled",
      group: "Content",
      label: "Enable pagination",
      description: "Whether the homepage shows pagination controls when there are more posts than fit on one page.",
      schema: z.boolean(),
      defaultValue: false,
      scope: "private",
    },
    {
      key: "content.home_pagination_style",
      group: "Content",
      label: "Pagination style",
      description: "Numbered (1, 2, 3, …) or arrows-only (Prev / Next).",
      schema: z.enum(["numbered", "arrows"]),
      defaultValue: "numbered",
      scope: "private",
    },
    {
      key: "content.home_pagination_type",
      group: "Content",
      label: "Pagination control type",
      description: "Render pagination as buttons or as plain links.",
      schema: z.enum(["buttons", "links"]),
      defaultValue: "buttons",
      scope: "private",
    },
    {
      key: "content.home_pagination_align",
      group: "Content",
      label: "Pagination alignment",
      description: "Horizontal alignment of pagination controls (left, center, right).",
      schema: z.enum(["left", "center", "right"]),
      defaultValue: "center",
      scope: "private",
    },
    {
      key: "content.disable_right_click",
      group: "Content",
      label: "Disable right-click on public pages",
      description:
        "Suppresses the browser context menu on the public site (/, /[slug]). " +
        "A soft deterrent against casual content lifting — not a security control. " +
        "Admin routes are unaffected.",
      schema: z.boolean(),
      defaultValue: false,
      scope: "public",
    },

    // ── System ───────────────────────────────────────────────────────────
    {
      key: "system.setup_complete",
      group: "System",
      label: "Setup complete",
      description: "Set to true after the first-run setup wizard finishes",
      schema: z.boolean(),
      defaultValue: false,
      scope: "private",
    },
  ]);
}
