import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseManifest, type PluginManifest } from "../../src/core/plugins/manifest";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ROOT = resolve(__dirname, "../..");
const SCAN_DIRS = [
  join(ROOT, "src/core-plugins"),
  join(ROOT, "plugins"),
  join(ROOT, "themes")
];
const OUT_FILE = join(ROOT, "src/generated/plugins.ts");
const BLOCKS_OUT_FILE = join(ROOT, "src/generated/plugin-blocks.ts");
const ADMIN_OUT_FILE = join(ROOT, "src/generated/plugin-admin-contributions.ts");

interface DiscoveredPlugin {
  manifest: PluginManifest;
  modulePath: string;
  migrationsDir: string | null;
  /** Path of the plugin's `theme-blocks.{ts,tsx}` file relative to the
   *  scan root, when present. The generated `plugin-blocks.ts` aggregator
   *  side-effect-imports each one so the block registry is populated on
   *  both server and client bundles. */
  themeBlocksModulePath: string | null;
  /** Path of the plugin's `admin-contributions.{ts,tsx}` file when
   *  present. The generated `plugin-admin-contributions.ts` aggregator
   *  side-effect-imports each one from the client-side admin form so
   *  contributed fieldsets land in the registry. */
  adminContributionsModulePath: string | null;
}

function aliasPrefixFor(scanDir: string): string {
  const rel = relative(ROOT, scanDir).replace(/\\/g, "/");
  if (rel === "src/core-plugins") return "@core-plugins";
  if (rel === "plugins") return "@plugins";
  if (rel === "themes") return "@themes";
  return rel;
}

function scan(): DiscoveredPlugin[] {
  const found: DiscoveredPlugin[] = [];

  for (const dir of SCAN_DIRS) {
    if (!existsSync(dir)) continue;
    const aliasPrefix = aliasPrefixFor(dir);
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const pluginDir = join(dir, entry.name);
      const manifestPath = join(pluginDir, "plugin.json");
      if (!existsSync(manifestPath)) continue;

      let manifest: PluginManifest;
      try {
        manifest = parseManifest(JSON.parse(readFileSync(manifestPath, "utf8")));
      } catch (err) {
        console.error(`[discover] invalid plugin.json at ${manifestPath}:`, err);
        continue;
      }

      const modulePath = `${aliasPrefix}/${entry.name}`;
      const migDir = join(pluginDir, "migrations");

      const tsxBlocks = join(pluginDir, "theme-blocks.tsx");
      const tsBlocks = join(pluginDir, "theme-blocks.ts");
      const hasTsxBlocks = existsSync(tsxBlocks);
      const hasTsBlocks = existsSync(tsBlocks);
      const themeBlocksModulePath = hasTsxBlocks || hasTsBlocks
        ? `${aliasPrefix}/${entry.name}/theme-blocks`
        : null;

      const tsxAdmin = join(pluginDir, "admin-contributions.tsx");
      const tsAdmin = join(pluginDir, "admin-contributions.ts");
      const hasAdmin = existsSync(tsxAdmin) || existsSync(tsAdmin);
      const adminContributionsModulePath = hasAdmin
        ? `${aliasPrefix}/${entry.name}/admin-contributions`
        : null;

      found.push({
        manifest,
        modulePath,
        migrationsDir: existsSync(migDir) ? migDir : null,
        themeBlocksModulePath,
        adminContributionsModulePath
      });
    }
  }

  return found.sort((a, b) => a.manifest.slug.localeCompare(b.manifest.slug));
}

function emit(plugins: DiscoveredPlugin[]): string {
  const header = `// AUTO-GENERATED by scripts/plugins/discover.ts. DO NOT EDIT.\n` +
                 `// Re-run: npm run plugins:discover\n\n` +
                 `import type { PluginManifest } from "@core/plugins/manifest";\n` +
                 `import type { PluginAPI } from "@core/plugins/api";\n\n`;

  const importLines = plugins
    .map((p, i) => `import * as plugin_${i} from "${p.modulePath}";`)
    .join("\n");

  const interfaceBlock = `export interface DiscoveredPluginEntry {\n` +
    `  manifest: PluginManifest;\n` +
    `  module: { default?: (api: PluginAPI) => void | Promise<void> };\n` +
    `  migrationsDir: string | null;\n` +
    `}\n\n`;

  const arrayBody = plugins.length === 0
    ? `export const discoveredPlugins: DiscoveredPluginEntry[] = [];\n`
    : `export const discoveredPlugins: DiscoveredPluginEntry[] = [\n` +
      plugins
        .map((p, i) => {
          const manifestJson = JSON.stringify(p.manifest, null, 2)
            .split("\n")
            .map((line, idx) => (idx === 0 ? line : `    ${line}`))
            .join("\n");
          const migPath = p.migrationsDir
            ? JSON.stringify(relative(ROOT, p.migrationsDir).replace(/\\/g, "/"))
            : "null";
          return `  {\n` +
                 `    manifest: ${manifestJson} as PluginManifest,\n` +
                 `    module: plugin_${i} as DiscoveredPluginEntry["module"],\n` +
                 `    migrationsDir: ${migPath}\n` +
                 `  }`;
        })
        .join(",\n") +
      `\n];\n`;

  return `${header}${importLines}${importLines ? "\n\n" : ""}${interfaceBlock}${arrayBody}`;
}

function emitBlocks(plugins: DiscoveredPlugin[]): string {
  const header =
    `// AUTO-GENERATED by scripts/plugins/discover.ts. DO NOT EDIT.\n` +
    `// Re-run: npm run plugins:discover\n` +
    `//\n` +
    `// Side-effect imports — each plugin's \`theme-blocks\` file calls\n` +
    `// \`registerPluginThemeBlocks\` at module-load. Both server\n` +
    `// (renderActiveTheme) and client (page editor, theme builder) bundles\n` +
    `// import this aggregator so the cross-surface block registry is\n` +
    `// populated identically on both sides. See\n` +
    `// \`docs/plugins/theme-widgets.mdx\` for the plugin-author contract.\n\n`;

  const importLines = plugins
    .filter((p) => p.themeBlocksModulePath !== null)
    .map((p) => `import "${p.themeBlocksModulePath}";`)
    .join("\n");

  // Always emit `export {}` so the file is treated as a module even when
  // no plugins ship theme-blocks files yet — keeps the import syntax in
  // consumers (`import "@generated/plugin-blocks"`) valid in either case.
  return `${header}${importLines}${importLines ? "\n\n" : ""}export {};\n`;
}

function emitAdminContributions(plugins: DiscoveredPlugin[]): string {
  const header =
    `// AUTO-GENERATED by scripts/plugins/discover.ts. DO NOT EDIT.\n` +
    `// Re-run: npm run plugins:discover\n` +
    `//\n` +
    `// Side-effect imports — each plugin's \`admin-contributions\` file\n` +
    `// calls \`registerPostEditFieldset\` (and any future admin-side\n` +
    `// registries) at module-load. The client-side admin form\n` +
    `// (PostEditForm) side-effect-imports this aggregator so contributed\n` +
    `// fieldsets land in the registry before the form's first render.\n\n`;

  const importLines = plugins
    .filter((p) => p.adminContributionsModulePath !== null)
    .map((p) => `import "${p.adminContributionsModulePath}";`)
    .join("\n");

  return `${header}${importLines}${importLines ? "\n\n" : ""}export {};\n`;
}

function main() {
  const plugins = scan();
  mkdirSync(join(ROOT, "src/generated"), { recursive: true });
  writeFileSync(OUT_FILE, emit(plugins));
  writeFileSync(BLOCKS_OUT_FILE, emitBlocks(plugins));
  writeFileSync(ADMIN_OUT_FILE, emitAdminContributions(plugins));
  const blockCount = plugins.filter((p) => p.themeBlocksModulePath !== null).length;
  const adminCount = plugins.filter((p) => p.adminContributionsModulePath !== null).length;
  console.log(`[discover] wrote ${plugins.length} plugin(s) to ${relative(ROOT, OUT_FILE)}`);
  console.log(`[discover] wrote ${blockCount} theme-block module(s) to ${relative(ROOT, BLOCKS_OUT_FILE)}`);
  console.log(`[discover] wrote ${adminCount} admin-contributions module(s) to ${relative(ROOT, ADMIN_OUT_FILE)}`);
  for (const p of plugins) {
    const blockNote = p.themeBlocksModulePath ? " [+theme-blocks]" : "";
    const adminNote = p.adminContributionsModulePath ? " [+admin]" : "";
    console.log(`  - ${p.manifest.slug} (${p.manifest.tier})${blockNote}${adminNote}`);
  }
}

main();
